version: "3.8"

services:

  traefik:
    image: "traefik:2.4"
    networks:
      - "traefik"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    command:
      - "--entrypoints.web.address=:80"
      - "--log.level=DEBUG"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker=true"

  nginx:
    image: "nginx:1.21-alpine"
    networks:
      - "traefik"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.default.rule=Host(`localhost`)"
      - "traefik.port=80"
    volumes:
      - "./docker-compose/nginx/templates:/etc/nginx/templates:ro"

  php-fpm:
    image: "php:5.6-fpm-alpine"
    networks:
      - "traefik"
    volumes:
      - ".:/var/www/html"

networks:
  traefik:
